/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo.vscode.junit5.debugger;

import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        App classUnderTest = new App();
        assertTrue(classUnderTest.getGreeting() != null);
    }
}
